### ISSUE TITLE
SPLIT na backend & frontend

### ISSUE THREAD

**Issue by vencax** [SmallhillCZ/Supervizor-Plus#115]
AD1: Takhle v zacatku bych hoooodne doporucoval rozdelit projekt na backend (API) a frontend (GUI) aby z toho v prubhu casu nevznikl chaoticky spletenec kodu + lepsi testovatelnost + lepsi rozdeleni zodpovednosti.
Co vy na to?

**Comment by vencax** [comment]
AD2: Za dalsi: vyvaroval bych se reseni nejake komprese, nebo nginx detailu. To s projektem VUBEC nesouvisi. To je otazka deploymentu. Na to muze vzniknout dalsi projekt (treba zabalujici frontend + backend do nginx served prostredi v DOCKERU).

**Comment by SmallhillCZ** [comment]
AD1: Na začátku jsme to tak měli, takhle nám to přišlo jednodušší na správu, ale zamyslím se, jestli není čas to zas oddělit. Kód backendu a frontendu držíme vlastně odděleně (složky server a ui), co se týče kódu, sdílejí pouze package.json. Je pro nás zkrátka jednodušší spouštět třeba test jedním příkazem, když je to pohromadě. 
 
AD2: Co se týče projektu jakožto git repo, tj. kódu, tak to spolu nesouvisí, s tím souhlasím. My používáme Issues tady na GitHubu na řešení i problémů mimo kód a vývoj, tj. proto ty zmínky o nginx, reálně ale nechceme deployment a vývoj mixovat (max. zahrnout vzorový config)

**Comment by vencax** [comment]
AD1: IMHO nazral a doporucuji to udelat co nejdriv.
AD2: ok, issues se muzou linkovat
AD3: __proc mongo?__ Obtizna testovatelnost, mensi rychlost  ... za me navrh: [ORM - bookshelfjs.org](http://bookshelfjs.org/) a testovat s sqlite (in memory).
PS: Jsem rad, ze otevrenamesta/mfcr konecne rozjela nejakou aktivitu. Rad budu napomocen ...

**Comment by SmallhillCZ** [comment]
AD3: kouknu na to, moc se v tom nevyznám. Ukládáme stromové JSONy s rozpadem dat, abychom už nemuseli nic procesovat při zobrazování, tak nám MongoDB přišla jako ideální.

Teď to potřebujeme dostat příštím týdnu do stabilní fáze a pak si určitě necháme pomoci/poradit.

**Comment by vencax** [comment]
OK, jakmile bude stable verze a releasnete ji, tak jsem pripraven pomoci formou: projekt splitnout a poslat pull requesty. Behem 1 dne.

**Comment by jirutka** [comment]
Souhlasím s @vencax, že MongoDB není moc dobrá volba. 

Doporučil bych PostgreSQL, je to mnohem stabilnější a spolehlivější DB, která umožňuje vhodně kombinovat klasický relační a dokumentový model při zachování plného ACID. Stromová data, nad kterými není potřeba moc vyhledávat, ukládat jako JSONB. PostgreSQL umožňuje dotazování i nad atributy zanořené v JSONB, je možné nad nimi postavit i indexy, ale přeci jen je primárně relační DB, takže je lepší data trochu normalizovat.

**Comment by SmallhillCZ** [comment]
Konečně budu mít zas čas k nějakému vývoji. Nicméně ani o jedné z těchto věcí nejsem vlastně přesvědčený, bylo by možné se někdy dohodnout a pobavit se o tom (třeba online)? Jde mi o následující:

Ad split: Jednotný repozitář na GH mi zajistí, že se mi nerozjedou verze API a GUI, což mi přijde důležité. Aplikaci vyvíjíme ve dvou a jednotné repo nám tedy nečiní žádné problémy. Z toho plyne i způsob vývoje, kdy funkcionalitu zpravidla implementujeme najednou jak na server side, tak na client side. Jaké jsou praktické výhody oddělení za takovéto situace?

Ad databáze: Souhlasím, že mi MongoDB přijde pomalejší, než by se mi líbilo, ale s PostgreSQL jsem nikdy nedělal a co jsem tak koukal na docs na netu, asi bych potřeboval trochu vysvětlit, jak jí používat na JSON storage stejně jako MongoDB. Kdybyste někdo byli ochotní mi s tím nějak poradit, velmi bych to ocenil.

Díky!

**Comment by vencax** [comment]
SPLIT jsem navrhoval hlavne kvuli tomu, ze lze pak mit team lidi, co umi backend a team, co umi frontend. PLUS jednotlive repos pak jsou prehlednejsi, protoze FE a BE pouzivaji jiny lib/tool set. Zkratka rozdel a panuj. ANO, nevyhoda je ze se muze API rozjet. Ale cilem je imho abyse API menilo minimalne.
NAVIC FE lze dale rodelit (a samostatne otestovat) na state cast (za me idealne pomoci mobx.js) a zobrazeni (frci React.js ale lze i jine FE knihovny dokonce vcetne angularu)

AD DB: s vhodnym ORM (napr. bookshelf.js) lze pouzit relacni DB bez vetsich zmen. 

PS: moc rad bych udelal nejaky nastrel, ale mel sem nehodu na moto a nemuzu min mesic pouzivat obe ruce, coz me diskvalifikovava od progtramovani ;/ Po zhlednuti kodu bych uvital, kdyby nekdo dopsal nejaky popis, co ktere casti delaji a doplnil treba i commenty v kodu. Je jasne, ze projekt stoji na scesti a bylo by imho fajn se vydat cestou, kdy do nej bude bez velkych studii mozne prispivat.

**Comment by SmallhillCZ** [comment]
Díky, na bookshelf určitě kouknu. Ohledně toho splitu to ještě projednáme s klukama z Otevřených měst. Doplnit komentáře v kódu je v plánu.

Přeju brzké uzdravení!
