### ISSUE TITLE
Glitch při výběru roků

### ISSUE THREAD

**Issue by vlasaty-oict** [SmallhillCZ/Supervizor-Plus#137]
![2018-03-09_11-09-48](https://user-images.githubusercontent.com/36531900/37202450-d3c7df6a-238a-11e8-8a01-fe4504ffa75d.gif)
win10/chrome

**Comment by SmallhillCZ** [comment]
Nechápu to :-D

**Comment by SmallhillCZ** [comment]
This issue was moved to CityVizor/CityVizor#17
