### ISSUE TITLE
harvestuje > shromažďuje, +URL?

### ISSUE THREAD

**Issue by nesnera** [SmallhillCZ/Supervizor-Plus#140]
Mám obavu, že jen málokdo zná termín "harvestuje". Navrhuji nahradit slovem "shromažďuje". Je na https://cityvizor.cz/<obec>/uredni-deska ve větě "Cityvizor využívá data z aplikace edesky.cz, která harvestuje data z jednotlivých úředních desek."

+může-li v popisu být odkaz, dal bych edesky.cz jako URL odkaz

**Comment by SmallhillCZ** [comment]
This issue was moved to CityVizor/CityVizor#13
