### ISSUE TITLE
nápověda při zakládání profilu obce

### ISSUE THREAD

**Issue by nesnera** [SmallhillCZ/Supervizor-Plus#141]
Při zakládání nové profilu z https://cityvizor.cz/admin/profily není u položek žádná nápověda narozdíl od https://cityvizor.cz/<obec>/admin/profil
Má velmi mízkou prioritu, neboť obce se nehrnou do režimu, kdy by si účet spravovaly samy.

**Comment by SmallhillCZ** [comment]
This issue was moved to CityVizor/CityVizor#15
