### ISSUE TITLE
V about rozlišit back|front end

### ISSUE THREAD

**Issue by nesnera** [SmallhillCZ/Supervizor-Plus#142]
Rozlišení back|front end je v about sice naznačeno přes URL, ale uvedl bych to i explicitně, ať ani laik není zmaten. Navrhuji:
"Zdrojový kód aplikace naleznete na GitHubu v repozitářích otevrena-data-mfcr/CityVizor a otevrena-data-mfcr/CityVizor-server." > "Zdrojový kód aplikace naleznete na GitHubu v repozitářích otevrena-data-mfcr/CityVizor (klient) a otevrena-data-mfcr/CityVizor-server (server)."
Možná bych tu serverou tady ani neuváděl - stejně ji nikdo zvenku nemůže připomínkovat a v READ.me odkaz na serverou je.

**Comment by SmallhillCZ** [comment]
This issue was moved to CityVizor/CityVizor#12
