### ISSUE TITLE
nízký limit na upload znaku obce

### ISSUE THREAD

**Issue by nesnera** [SmallhillCZ/Supervizor-Plus#143]
Aktuální limit je 100 KiB, ale velikost např. [SVG znaku Prahy 9](https://commons.wikimedia.org/wiki/File:Praha-09_CoA.svg) je 332 KiB (musel jsem použít PNG s 256px). Předpokládám, že u propracovanějších znaků to bude celkem běžná velikost, navrhuji tedy zvýšení.

**Comment by SmallhillCZ** [comment]
This issue was moved to CityVizor/CityVizor#11
