### ISSUE TITLE
zkontrolovat vzorová data | aplikace

### ISSUE THREAD

**Issue by nesnera** [SmallhillCZ/Supervizor-Plus#147]
data viz. issue https://github.com/otevrena-data-mfcr/CityVizor/issues/146
- na web CV je nelze nahrát
- demo aplikace je sice načte, ale vizualizace nevypadá, že by s nimi korespondovala :-/

**Comment by SmallhillCZ** [comment]
This issue was moved to CityVizor/CityVizor#7
