### ISSUE TITLE
Připravit na PM2 / běh více instancí na jednom serveru

### ISSUE THREAD

**Issue by VojtaStanek** [SmallhillCZ/Supervizor-Plus#53]
Asi nechcete, aby to běželo jen jako jedna instance (pokud ano, tak to bude asi dost pomalé a případně i nestabilní). Určitě to nepřežijí crony (nevím jak se to bude přesně chovat, ale spustí se na každé instanci zvlášť, tj. do jednoho souboru budou zapisovat dva najednou, což asi není nejlepší věc)

**Comment by SmallhillCZ** [comment]
Jo, tohle plánujeme řešit někdy v létě v rámci předání aplikace na Otevřená města. Já tomu totiž vůbec nerozumim.

Kromě výkyvů po tiskovce apod. neočekáváme aspoň ze začátku větší nápor. Netuším kolik to je schopné odbavit při jediné instanci. Chtěl jsem to zkusit teď přes Apache Benchmark, ale vysloužil jsem si akorát zablokování přístupu do internetu na pár minut :)

**Comment by SmallhillCZ** [comment]
@Kedrigern: Mohl by ses poptat po někom u vás, kdo tomu rozumí?
