### ISSUE TITLE
MongoDB injection (as in SQLi)

### ISSUE THREAD

**Issue by VojtaStanek** [SmallhillCZ/Supervizor-Plus#54]
Jde o chybu zde: https://github.com/otevrena-data-mfcr/CityVizor/blob/master/server/api/login.js#L31

Když dám request s tímto body, tak to bude fungovat (najde to uživatele admin): 
```JSON
{
  "login": {"$exists": true},
  "password": "admin"
}
```

Případně lze pomocí `$not: {$in: []}` nalézt všechny uživatele a posílat jim phising emaily. ;)

**Comment by SmallhillCZ** [comment]
Díky moc, přiznám se, že jsme to zatím neřešili, soustředili jsme se na client-side. Myslíš, že https://github.com/efkan/content-filter je dostatečné řešení?

**Comment by VojtaStanek** [comment]
Asi ano, byť možná mohlo být lepší `body` a `query` validovat proti json schematu (existují express middlewary, co to dělají). 

(Jenom dodávám, že jsem s tím nikdy nedělal, je to jenom nápad.)

**Comment by SmallhillCZ** [comment]
jo vidiš to se mi líbí asi nejvíc. díky!

**Comment by VojtaStanek** [comment]
Ono by z toho šlo i generovat api dokumentaci...

**Comment by VojtaStanek** [comment]
:+1:
