### ISSUE TITLE
Jde listovat všechny ETL, nejen vlastní

### ISSUE THREAD

**Issue by VojtaStanek** [SmallhillCZ/Supervizor-Plus#55]
(Nevím co je ETL ale to je vlastně jedno...)

Prvně člověk musí mít účet (`req.user`) a managovat nějaký profile.
Vezměme například GET dotaz na `/api/etl` (https://github.com/otevrena-data-mfcr/CityVizor/blob/master/server/api/etl.js). V body dotazu (i get podle všeho může mít body, přestože se to nepoužívá) je JSON objekt, kde v profile je profileId nějakého profilu, který uživatel spravuje. (https://github.com/otevrena-data-mfcr/CityVizor/blob/master/server/acl/profile-manager.js#L1-L4)

V URL je ale něco jako `?profile[$exists]=true`. Případně by stačilo i  `?profile=123` (kde 123 je cizí profile) Takže mongoDb dostane dotaz `{profile: {$exists: true}}` a vrátí všechno. Hurá, heknuto! 

Funkčnost jsem neověřoval... Ale mělo by to tak být...

**Comment by SmallhillCZ** [comment]
Teď by nemělo jít zobrazit ETL nemanageovaného profilu. Co se týče ```?profile[$exists]=true```, tak to budeme řešit v rámci #54.
