### ISSUE TITLE
Graf rozpočtu- špatné přetáčení 

### ISSUE THREAD

**Issue by Kuba-testing** [SmallhillCZ/Supervizor-Plus#61]
Pří překlikávání mezi jednotlivými kapitolami rozpočtu se graf posouvá pravidelně, když se však v jeden okamžik klikne na jednu z kapitol tak se celý graf přetočí o víc jak 180. Nerozumím tomu, ale asi je graf naprogramován že se dá klikat jen z jedné strany a po překročení 360 se přetáčí.
![divne pretaceni](https://cloud.githubusercontent.com/assets/28958169/26600206/77ed7e4a-457b-11e7-8c3c-769c068b82de.JPG)

**Comment by SmallhillCZ** [comment]
Jo, já vim... je to tím, že každá kategorie má nastavený počet stupňů o kolik se má otočit graf. První má nula, druhá 360/počet skupin atd. až poslendí má něco pod 360. A je tamnastavená animace aby se to neotáčelo skokem. Jenže ty animace jsou hloupý a nechápou, že 360 je kruh, a berou to jenom jako číslo. Takže z poslední na první je to z 350 stupňů na 0 místo na 360.

Ale už jsem vymyslel jak to opravit, ty stupně se budou nastavovat inteligentněji, ve vztahu k tomu, co je teď vybraný.
