### ISSUE TITLE
Karta nastavení po přihlášení je prázdná

### ISSUE THREAD

**Issue by Kuba-testing** [SmallhillCZ/Supervizor-Plus#65]
Po přihlášení k účtu test-profile-manager jsem se snažil otevřít nastavení a něco změnit, to však nešlo. 
Zobrazila se mi jen prázdná stránka (viz screen1) poté jsem se snažil vrátit na přehled (NMNM) to však také nešlo, zobrazila se mi prázdná stránka s jinou adresou. (viz screen  2)
screen1
![image](https://user-images.githubusercontent.com/28958169/26852530-dbbf978a-4b0e-11e7-843a-ccfc398e8755.png)
screen 2
![image](https://user-images.githubusercontent.com/28958169/26852924-3f277c1a-4b10-11e7-9ad3-4c17ea305b29.png)

**Comment by SmallhillCZ** [comment]
upřímně si nevybavuju, že bych to opravoval, ale nedaří se mi to zreprodukovat, tak to uzavírám..
