### ISSUE TITLE
Chybná změna hesla

### ISSUE THREAD

**Issue by Kuba-testing** [SmallhillCZ/Supervizor-Plus#66]
U účtu test-admin jsem se snažil změnit heslo po zadání nového hesla jsem zadal potvrzující heslo chybně aplikace však zobrazila ikonu ukládání.
Očekával jsem zahlášení chyby, že se neshodují údaje.
Později po opětovném zadaní hesla se mi nedaří se zpět do účtu přihlásit.
Test proběhl v Chromu
![image](https://user-images.githubusercontent.com/28958169/26853841-e81475d2-4b13-11e7-8d66-4ae7a0cfb3a7.png)

**Comment by SmallhillCZ** [comment]
koukal jsem na to, problém by měl být jen v tom, že se neověřuje zadání nového hesla, nicméně to první by se mělo v pořádku nastavit.
