### ISSUE TITLE
Nefungující filtry v záložce Investice

### ISSUE THREAD

**Issue by Kuba-testing** [SmallhillCZ/Supervizor-Plus#67]
V záložce Investice jsem se snažil užít jednoho ze tři filtrů, (Objem, nejnovější a období) kliknutí na ikony filtrů je však bez jakékoli odezvy. Čekal jsem, že se obsah záložky přizpůsobí zvolenému filtru. 
![image](https://user-images.githubusercontent.com/28958169/26854270-b480a07c-4b15-11e7-937b-365d87815233.png)

**Comment by SmallhillCZ** [comment]
Tohle je potřeba nějak víc domyslet. Možná to na to úvodní testování dokonce dáme uplně pryč. Rozmyslíte to prosím nějak @janvlasaty a @BenediktKotmel? Ď

**Comment by SmallhillCZ** [comment]
Záložka byla zrušena
