### ISSUE TITLE
Chybně fungující filtr na města (úvodní strana)

### ISSUE THREAD

**Issue by Kuba-testing** [SmallhillCZ/Supervizor-Plus#70]
Na úvodní stránce jsem se snažil použít filtr na hledání měst. Zkusil jsem zadat N a poté O (jako Nové město), filtr mi však město našel až po zadání písmena V. Když jsem se pokusil zadat samostatné V tak mi to ukázalo odkaz na Nové město. Očekával jsem, že po zadání písmenek N a O se objeví odkaz na Nové město a po zadání písmena V se neukáže nic, jelikož takové město v systému zatím není.

![image](https://user-images.githubusercontent.com/28958169/27393959-f6bdb3f8-56aa-11e7-81bd-c08781f77b09.png)
![image](https://user-images.githubusercontent.com/28958169/27394254-d0252932-56ab-11e7-948e-f040b1fa2ff4.png)

**Comment by SmallhillCZ** [comment]
to je "feature, no a bug" :-D 

Hledá to i ve slově, ne jen od začátku. Tj. pro NO to najde všechny... NOvé město, čerNOšice, brNO

**Comment by Kuba-testing** [comment]
A jo to mi nedošlo :D

**Comment by SmallhillCZ** [comment]
Dohodli jsme se že by to mělo vyhledávat od začátků slov. Opraveno v 8355f4f251b104ce070ec36e017ba73649e559f6
