### ISSUE TITLE
Nefunkční odkazy v dokumentaci CitiVizoru

### ISSUE THREAD

**Issue by Kuba-testing** [SmallhillCZ/Supervizor-Plus#74]
V dokumentaci k aplikaci Citivizoru jsem se snažil užít odkazy JSON, CVS a Přejít na citivizor. Po kliknutí se mi požadovaný odkaz neotevřel. Očekával jsem, že se mi otevře požadovaný odkaz.
![image](https://user-images.githubusercontent.com/28958169/27507535-922ac0c4-58d1-11e7-9979-ed8f9184c09f.png)

![image](https://user-images.githubusercontent.com/28958169/27507534-8d82cc24-58d1-11e7-9d49-a3e9dc0e6832.png)

**Comment by SmallhillCZ** [comment]
Vyřešeno, odkazy vedly na ostrou verzi, která ještě nebyla spuštěna - už je.
