### ISSUE TITLE
Není jak otevřít skryté město, které můžu editovat

### ISSUE THREAD

**Issue by Kuba-testing** [SmallhillCZ/Supervizor-Plus#75]
Po přihlášení k účtu test-profile-manager jsem se snažil dostat k přístupu do města ke kterému má tento účet pravomoc (Nové Město). Z úvodní strany jsem se snažil najít odkaz na dané město, ten zde však chybí. Čekal jsem, že po přihlášení se mi otevře dané město ke kterému má tento účet pravomoc, nebo že pomocí kliknutí toto město se bude moct otevřít na úvodní straně.
![image](https://user-images.githubusercontent.com/28958169/27507643-50ca3608-58d3-11e7-992f-42af63fa0804.png)

**Comment by SmallhillCZ** [comment]
jo už to vidim, díky
