### ISSUE TITLE
Nefunkční odkazy na Fb a Twitter a špatně nastavená grafika odkazů

### ISSUE THREAD

**Issue by Kuba-testing** [SmallhillCZ/Supervizor-Plus#76]
Na úvodní stránce jsem se snažil užít odkazů na sociální sítě. Po kliknutí na odkazy se nic nestalo. Čekal jsem otevření odkazů. Při najetí kurzorem na odkaz se mírně rozhodí grafika (vedle odkazu vznikne pomlčka).
![image](https://user-images.githubusercontent.com/28958169/27507756-20dc836c-58d6-11e7-9404-5bdc84e8c725.png)

**Comment by SmallhillCZ** [comment]
Super, kouknu na to
