### ISSUE TITLE
Verze pro embed

### ISSUE THREAD

**Issue by Kedrigern** [SmallhillCZ/Supervizor-Plus#91]
Častým využitím bude embedování strániky do webu obce.

Pro začátek by stačil nějaký parametr, který by skryl vše krom hlavního divu. A to by se jednoduše vložilo jako iframe.

**Comment by SmallhillCZ** [comment]
Uděláme speciální embedovací prvky, celá stránka by na embedování nebyla hezká.

**Comment by SmallhillCZ** [comment]
This issue was moved to CityVizor/CityVizor#24
