### ISSUE TITLE
Špatně řazený seznam měst

### ISSUE THREAD

**Issue by JakubSlavik** [SmallhillCZ/Supervizor-Plus#96]
Na úvodní stránce jsou špatně zařazená města začínající na stejné písmeno tedy N. Jsou řazeny vedle sebe což mi připadá nepřehledné. Města by byla přehlednější v řazení pod sebou.
![image](https://user-images.githubusercontent.com/30458421/28606366-037120d4-71d7-11e7-8b9f-8deaafcbd21b.png)

**Comment by SmallhillCZ** [comment]
Vyřeší se v #102
