### ISSUE TITLE
Nefungující upozornění na vložení špatných dat v Importu účetních dat

### ISSUE THREAD

**Issue by JakubSlavik** [SmallhillCZ/Supervizor-Plus#97]
V importu účetních dat jsem se snažil nahrát soubory ve správném formátu, ale ve špatném pořadí (Events, Expenditures) po kliknutí nahrát se neobjevilo žádné upozornění, nic nenastalo. Čekal jsem upozornění že soubory neodpovídají.
![image](https://user-images.githubusercontent.com/30458421/28609119-9870e5aa-71e3-11e7-8588-573842337cd0.png)

**Comment by SmallhillCZ** [comment]
duplicate of #99
